main:
  project_name: glaucoma-detection
  experiment_name: dev
data:
  bucket_name: glaucoma-dataset
  source_blob_name: data.zip
  url: https://storage.googleapis.com/glaucoma-dataset/data.zip
  dir_name: data
trainer:
  data_path: ./data
  data_csv_path: ./data/dataset/dummy_train_data.csv
  test_data_csv_path: ./data/dataset/dummy_test_data.csv
  model_path: ./model/modelWeights_0.0001lrBs16.pth
  image_path: ./data/dataset/1/TRAIN021661.jpg
  data_url: https://storage.googleapis.com/glaucoma-dataset/data.zip
  batch_size: 2
  lr: 0.001
  num_epochs: 2
  validate_only: False