main:
  project_name: glaucoma-detection
  experiment_name: dev
data:
  bucket_name: glaucoma-dataset
  source_blob_name: data.zip
  url: https://storage.googleapis.com/glaucoma-dataset/data.zip
  dir_name: data